name: Deploy HTML Page

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install Apache2
      run: sudo apt install apache2 -y
      
    - name: Copy files to /var/www/html
      run: rsync -avz --delete . /var/www/html/
      
    - name: Check Apache2 status
      run: sudo systemctl status apache2 || sudo systemctl start apache2
      
    - name: Restart Apache2
      run: |
        sudo systemctl restart apache2
        sleep 2
